# vi:ft=ruby
Vagrant::Config.run do |config|
  config.vm.box = "centos"

  # Boot with a GUI so you can see the screen. (Default is headless)
  config.vm.boot_mode = :gui

  config.vm.forward_port "http", 80, 8080

  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "beatshuffle.pp"
  end
  
  
end
